kind: pipeline
name: testing

clone:
  depth: 50

steps:
- name: testing
  image: golang:1.11
  pull: true
  commands:
  - go get -u bitbucket.org/danil/go_rsa_signaturea
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u github.com/fzipp/gocyclo
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/gordonklaus/ineffassign
  - go get -u github.com/kisielk/errcheck
  - go get -u github.com/mdempsky/unconvert
  - go clean ./...
  - golint -set_exit_status ./...
  - go vet ./...
  - errcheck -verbose -asserts ./...
  - unconvert -v .
  - gocyclo -over 40 ./
  - ineffassign ./
  - misspell -error ./* ./*/* ./*/*/* ./*/*/*/* ./*/*/*/*/* ./*/*/*/*/*/* ./*/*/*/*/*/*/*
  - go test -v ./...
  - go test -race ./...
